wandb_version: 1

embedding_layer:
  value: word2vec
hidden_size:
  value: 600
loss_funct:
  value: CrssEntrop+UnivSntcEnc_cosDist
num_layers:
  value: 3
optimizer:
  value:
    lr: 0.006590764483688645
    type: adam
