wandb_version: 1

embedding_layer:
  value: word2vec
hidden_size:
  value: 600
loss_funct:
  value: CrssEntrop+UnivSntcEnc_cosDist
num_layers:
  value: 1
optimizer:
  value:
    lr: 0.006669669356589
    type: adam
