wandb_version: 1

embedding_layer:
  value: word2vec
hidden_size:
  value: 30
loss_funct:
  value: CrssEntrop+UnivSntcEnc_cosDist
num_layers:
  value: 6
optimizer:
  value:
    lr: 0.0012075857953062175
    type: adam
