wandb_version: 1

embedding_layer:
  value: word2vec
hidden_size:
  value: 30
loss_funct:
  value: CrssEntrop+UnivSntcEnc_cosDist
num_layers:
  value: 1
optimizer:
  value:
    lr: 0.0044921198873523905
    type: adam
