wandb_version: 1

embedding_layer:
  value: learnt
hidden_size:
  value: 300
loss_funct:
  value: CrssEntrop+UnivSntcEnc_cosDist
num_layers:
  value: 6
optimizer:
  value:
    lr: 0.0076744239310252765
    type: adam
