wandb_version: 1

embedding_layer:
  value: word2vec
hidden_size:
  value: 22
loss_funct:
  value: crossentropy
num_layers:
  value: 2
optimizer:
  value:
    lr: 0.0001673093957722688
    type: adam
