wandb_version: 1

embedding_layer:
  value: word2vec
hidden_size:
  value: 600
loss_funct:
  value: crossentropy
num_layers:
  value: 6
optimizer:
  value:
    lr: 0.00031803275004560846
    type: adam
