wandb_version: 1

embedding_layer:
  desc: null
  value: learnt
hidden_size:
  desc: null
  value: 20
loss_funct:
  desc: null
  value: crossentropy
num_layers:
  desc: null
  value: 2
optimizer:
  desc: null
  value:
    lr: 0.007374100054694683
    type: adam
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1684960340.431896
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.10.9
      5: 0.15.2
      8:
      - 1
      - 4
      - 5
