wandb_version: 1

embedding_layer:
  desc: null
  value: learnt
hidden_size:
  desc: null
  value: 300
loss_funct:
  desc: null
  value: CrssEntrop+UnivSntcEnc_cosDist
num_layers:
  desc: null
  value: 1
optimizer:
  desc: null
  value:
    lr: 0.004229375575156248
    type: adam
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.29.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1684961760.142136
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.15.2
      6: 4.29.0
      8:
      - 1
      - 4
      - 5
