wandb_version: 1

embedding_layer:
  value: word2vec
hidden_size:
  value: 300
loss_funct:
  value: CrssEntrop+UnivSntcEnc_cosDist
num_layers:
  value: 1
optimizer:
  value:
    lr: 0.002144159045956839
    type: adam
