wandb_version: 1

embedding_layer:
  value: word2vec
hidden_size:
  value: 1200
loss_funct:
  value: CrssEntrop+UnivSntcEnc_cosDist
num_layers:
  value: 6
optimizer:
  value:
    lr: 0.00039773661108469423
    type: adam
