wandb_version: 1

embedding_layer:
  value: learnt
hidden_size:
  value: 300
loss_funct:
  value: CrssEntrop+UnivSntcEnc_cosDist
num_layers:
  value: 1
optimizer:
  value:
    lr: 0.005681889087496499
    type: adam
