wandb_version: 1

method:
  desc: null
  value: bayes
metric:
  desc: null
  value:
    name: Validation_Epoch_Loss
    goal: minimize
parameters:
  desc: null
  value:
    loss_funct:
      values:
      - crossentropy
      - CrssEntrop+UnivSntcEnc_cosDist
    embedding_layer:
      values:
      - word2vec
      - learnt
    hidden_size:
      values:
      - 30
      - 300
      - 600
      - 1200
    num_layers:
      values:
      - 1
      - 3
      - 6
    optimizer:
      parameters:
        type:
          values:
          - adam
        lr:
          distribution: uniform
          min: 5.0e-05
          max: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1684952136.913619
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.9
      5: 0.15.2
      8:
      - 1
      - 4
      - 5
