wandb_version: 1

embedding_layer:
  value: learnt
hidden_size:
  value: 1200
loss_funct:
  value: CrssEntrop+UnivSntcEnc_cosDist
num_layers:
  value: 1
optimizer:
  value:
    lr: 0.0016250407071768812
    type: adam
