wandb_version: 1

embedding_layer:
  value: learnt
hidden_size:
  value: 30
loss_funct:
  value: CrssEntrop+UnivSntcEnc_cosDist
num_layers:
  value: 3
optimizer:
  value:
    lr: 0.0015428175349282544
    type: adam
