wandb_version: 1

embedding_layer:
  value: word2vec
hidden_size:
  value: 300
loss_funct:
  value: CrssEntrop+UnivSntcEnc_cosDist
num_layers:
  value: 6
optimizer:
  value:
    lr: 0.006367313802258696
    type: adam
